// lib/react/keyboard.jsx
import React from 'react'
import { Options, Interface } from '../func/keyboard'
import '../style/keyboard.styl'

const rfirst = /^[a-z]/

class Parent extends React.Component {}
Object.assign(Parent.prototype, Interface)

export default class Keyboard extends Parent {
  constructor(props) {
    super(props)
    this.init(props)
  }

  dispatch(event, ...args) {
    this.props[`on${event.replace(rfirst, s => s.toUpperCase())}`](...args)
  }

  render() {
    const { _layout, _keys } = this
    return <div className="numeric-keyboard">
      <table>
        <tbody>
          {_layout.map((r, i) =>
            <tr key={i}>
              {r.map(c =>
                <td
                  key={c.key}
                  rowSpan={c.rowspan}
                  colSpan={c.colspan}
                  data-icon={_keys[c.key].icon}
                  style={_keys[c.key].style}
                  onTouchStart={e => this.ontouchstart(_keys[c.key], e)}
                  onTouchEnd={e => this.ontouchend(_keys[c.key], e)}>
                </td>
              )}
            </tr>
          )}
        </tbody>
      </table>
    </div>
  }
}

Keyboard.defaultProps = Options

// lib/vue/keyboard.vue
<template>
  <div class="numeric-keyboard">
    <table>
      <tr v-for="(r, i) in _layout" :key="i">
        <td v-for="c in r"
          :key="c.key"
          :rowspan="c.rowspan"
          :colspan="c.colspan"
          :data-icon="_keys[c.key].icon"
          :style="_keys[c.key].style"
          @touchstart="ontouchstart(_keys[c.key], $event)"
          @touchend="ontouchend(_keys[c.key], $event)">
        </td>
      </tr>
    </table>
  </div>
</template>

<script>

import { Options, Interface } from '../func/keyboard'

export default {
  mixins: [{
    methods: Interface
  }],
  props: (function () {
    let props = {}
    for (let name in Options) {
      props[name] = {
        default: Options[name]
      }
    }
    return props
  })(),
  data() {
    return {
      _layout: null,
      _keys: null
    }
  },
  created() {
    this.init(this._props)
  },
  methods: {
    dispatch(event, ...args) {
      this.$emit(event, ...args)
    }
  }
}

</script>

<style lang="stylus" src="../style/keyboard.styl"></style>
