// demo/react/app.jsx
import React from 'react'
import { NumericKeyboard, NumericInput, keys } from 'numeric-keyboard'
import './app.styl'

const PasswordLayout = [
  [
    {
      key: keys.ONE
    },
    {
      key: keys.TWO
    },
    {
      key: keys.THREE
    },
  ],
  [
    {
      key: keys.FOUR
    },
    {
      key: keys.FIVE
    },
    {
      key: keys.SIX
    },
  ],
  [
    {
      key: keys.SEVEN
    },
    {
      key: keys.EIGHT
    },
    {
      key: keys.NINE
    },
  ],
  [
    {
      key: keys.BLANK
    },
    {
      key: keys.ZERO
    },
    {
      key: keys.DEL
    },
  ],
]

class Password extends React.Component {
  constructor() {
    super()
    this.state = {
      password: ''
    }
  }

  press(key) {
    if (key === keys.DEL) {
      this.setState(state => ({ password: state.password.slice(0, -1) }))
    }
    else {
      this.setState(state => ({ password: state.password + key }), () => {
        if (this.state.password.length === 6) {
          setTimeout(() => this.props.onConfirm.call(null, this.state.password), 100)
        }
      })
    }
  }

  render() {
    return <section className="password">
      <div className="dialog">
        <h2>Conform password</h2>
        <div className="input">
          {[1, 2, 3, 4, 5, 6].map(n => n > this.state.password.length ? <span key={n}></span> : <span key={n} className="fill"></span>)}
        </div>
        <NumericKeyboard layout={PasswordLayout} onPress={this.press.bind(this)} />
      </div>
    </section>
  }
}

export default class App extends React.Component {
  constructor() {
    super()
    this.state = {
      amount: null,
      shouldOpenPassword: false
    }
  }

  inputAmout(amount) {
    this.setState({ amount: amount })
  }

  confirmAmount(e) {
    if (e) {
      e.preventDefault()
    }
    if (this.state.amount) {
      this.setState({ shouldOpenPassword: true })
    }
  }

  confirmPassword(password) {
    this.setState({ shouldOpenPassword: false })
    setTimeout(() => alert(`Amount: ${this.state.amount}\nPassword: ${password}`), 200)
  }

  render() {
    return <main className="app">
      <header>
        <h1>Transfer to Arthur</h1>
      </header>
      <form onSubmit={this.confirmAmount.bind(this)}>
        <label>Amount</label>
        <div className="input">
          <NumericInput type="number" autofocus entertext="Confirm" format="^(?:\d+(?:\.\d{0,2})?)?$" onInput={this.inputAmout.bind(this)} onEnterpress={this.confirmAmount.bind(this)} />
        </div>
        <input type="submit" value="Confirm" disabled={!this.state.amount} />
      </form>
      <footer>
        <p>Power by Numeric Keyboard</p>
      </footer>
      { this.state.shouldOpenPassword && <Password onConfirm={this.confirmPassword.bind(this)} /> }
    </main>
  }
}

// demo/transfer/angular/app/app.component.ts
import { Component, EventEmitter, Output } from '@angular/core'
import { Keys } from 'numeric-keyboard'

const PasswordLayout = [
  [
    {
      key: Keys.ONE
    },
    {
      key: Keys.TWO
    },
    {
      key: Keys.THREE
    },
  ],
  [
    {
      key: Keys.FOUR
    },
    {
      key: Keys.FIVE
    },
    {
      key: Keys.SIX
    },
  ],
  [
    {
      key: Keys.SEVEN
    },
    {
      key: Keys.EIGHT
    },
    {
      key: Keys.NINE
    },
  ],
  [
    {
      key: Keys.BLANK
    },
    {
      key: Keys.ZERO
    },
    {
      key: Keys.DEL
    },
  ],
]

const PasswordTemplate = `
<section class="password">
  <div class="dialog">
    <h2>Conform password</h2>
    <div class="input">
      <span *ngFor="let n of [1, 2, 3, 4, 5, 6]" [ngClass]="{ 'fill': n <= password.length }"></span>
    </div>
    <numeric-keyboard class="numeric-keyboard" [layout]="PasswordLayout" (press)="press($event)"></numeric-keyboard>
  </div>
</section>
`

@Component({
  selector: 'password',
  template: PasswordTemplate,
  styleUrls: [ './app.component.styl' ]
})
export class Password {
  @Output() confirm = new EventEmitter<string>()

  public PasswordLayout: any = PasswordLayout
  public password: string = ''

  press(key) {
    if (key === Keys.DEL) {
      this.password = this.password.slice(0, -1)
    }
    else {
      this.password = this.password + key
      if (this.password.length === 6) {
        setTimeout(() => this.confirm.emit(this.password), 100)
      }
    }
  }
}

const AppTemplate = `
<main class="app">
  <header>
    <h1>Transfer to Arthur</h1>
  </header>
  <form (submit)="confirmAmount($event)">
    <label>Amount</label>
    <div class="input">
      <numeric-input class="numeric-input" type="number" autofocus entertext="Confirm" format="^(?:\\d+(?:\\.\\d{0,2})?)?$" [(ngModel)]="amount" (enterpress)="confirmAmount()"></numeric-input>
    </div>
    <input type="submit" value="Confirm" [disabled]="!amount" />
  </form>
  <footer>
    <p>Power by Numeric Keyboard</p>
  </footer>
  <password *ngIf="shouldOpenPassword" (confirm)="confirmPassword($event)"></password>
</main>
`

@Component({
  selector: '#app',
  template: AppTemplate,
  styleUrls: [ './app.component.styl' ]
})
export class App {
  public amount: string | number = ''
  public shouldOpenPassword: boolean = false

  confirmAmount(e) {
    if (e) {
      e.preventDefault()
    }
    if (this.amount) {
      this.shouldOpenPassword = true
    }
  }

  confirmPassword(password) {
    this.shouldOpenPassword = false
    setTimeout(() => alert(`Amount: ${this.amount}\nPassword: ${password}`), 200)
  }
  
}
