// demo/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.styl' ]
})
export class AppComponent {
  public keyboardOutput: string
  public val: string | number

  get inputOutput() {
    return `${typeof this.val}: ${this.val}`
  }

  press(key) {
    this.keyboardOutput = `${typeof key}: ${key}`
  }
}

<div class="app">
  <h1 class="title">Numeric keyboard</h1>
  <section class="keyboard">
    <numeric-keyboard class="numeric-keyboard" layout="tel" entertext="send" (onPress)="press($event)"></numeric-keyboard>
    <p class="output">{{keyboardOutput}}</p>
  </section>
  <section class="input">
    <numeric-input class="numeric-input" type="number" placeholder="touch to input" format="^(?:\d+(?:\.\d{0,2})?)?$" [(ngModel)]="val"></numeric-input>
    <p class="output">{{InputOutput}}</p>
  </section>
</div>

// demo/react/app.jsx
import React from 'react'
import { NumericKeyboard, NumericInput, keys } from 'numeric-keyboard'
import './app.styl'

export default class App extends React.Component {
  constructor() {
    super()
    this.state = {
      keyboardOutput: null,
      inputOutput: null
    }
  }

  press(key) {
    this.setState({
      keyboardOutput: `${typeof key}: ${key}`
    })
  }

  input(val) {
    this.setState({
      inputOutput: `${typeof val}: ${val}`
    })
  }

  render() {
    return <div className="app">
      <h1 className="title">Numeric keyboard</h1>
      <section className="keyboard">
        <NumericKeyboard layout="tel" entertext="send" onPress={this.press.bind(this)} />
        <p className="output">{this.state.keyboardOutput}</p>
      </section>
      <section className="input">
        <NumericInput type="number" placeholder="touch to input" format="^(?:\d+(?:\.\d{0,2})?)?$" onInput={this.input.bind(this)} />
        <p className="output">{this.state.inputOutput}</p>
      </section>
    </div>
  }
}
