// demo/vue/app.vue
<template>
  <div class="app">
    <h1>Numeric keyboard</h1>
    <div class="keyboard">
      <NumericKeyboard layout="tel" :theme="telTheme" entertext="send" @press="press"></NumericKeyboard>
      <p v-if="keyPressed == null" class="keyboard-output">Press the keyboard</p>
      <p v-else class="keyboard-output">Key({{keyPressed}}) is pressed</p>
    </div>
    <hr>
    <div class="input">
      <NumericInput type="number" placeholder="touch to input" format="^(?:\d+(?:\.\d{0,2})?)?$" v-model="amount" />
      <button @click="clear">clear</button>
    </div>
  </div>
</template>

<script>
  import { NumericKeyboard, NumericInput, keys } from 'numeric-keyboard'
  export default {
    components: {
      NumericKeyboard,
      NumericInput
    },
    data() {
      return {
        amount: null,
        telTheme: {
          key: {
            [keys.DEL]: {
              color: '#ffffff',
              backgroundColor: ['#a8b0bc', '#929ba8']
            },
            [keys.ENTER]: {
              color: '#ffffff',
              backgroundColor: ['#a8b0bc', '#929ba8']
            }
          }
        },
        keyPressed: null,
      }
    },
    methods: {
      press(key) {
        this.keyPressed = key
      },
      clear() {
        this.amount = null
      }
    }
  }
</script>

<style lang="stylus">
  body
    font-size 0.24rem
    padding 0.32rem
  h1
    text-align center
  .keyboard
    .numeric-keyboard
      height 3.6rem
      border 1px solid #cfd4da
    .keyboard-output
      font-size 0.32rem
  .input
    .numeric-input
      font-size 0.36rem
      height 0.48rem
      border 1px solid #cfd4da
</style>

// demo/react/app.jsx
import React from 'react'
import { NumericKeyboard, NumericInput, keys } from 'numeric-keyboard'
import './app.styl'

export default class App extends React.Component {
  constructor() {
    super()
    this.state = {
      keyPressed: null
    }
  }

  press(key) {
    this.setState({
      keyPressed: key
    })
  }

  clear() {
    
  }

  render() {
    return <div className="app">
      <h1>Numeric keyboard</h1>
      <div className="keyboard">
        <NumericKeyboard layout="tel" theme={this.props.telTheme} entertext="send" onPress={this.press.bind(this)} />
        <p className="keyboard-output">{this.state.keyPressed != null ? `Key(${this.state.keyPressed}) is pressed`: 'Press the keyboard'}</p>
      </div>
      <div className="input">
        <NumericInput type="number" placeholder="touch to input" format="^(?:\d+(?:\.\d{0,2})?)?$" />
        <button onClick={this.clear.bind(this)}>Clear</button>
      </div>
    </div>
  }
}

App.defaultProps = {
  telTheme: {
    key: {
      [keys.DEL]: {
        color: '#ffffff',
        backgroundColor: ['#a8b0bc', '#929ba8']
      },
      [keys.ENTER]: {
        color: '#ffffff',
        backgroundColor: ['#a8b0bc', '#929ba8']
      }
    }
  }
}
